"""empty message

Revision ID: 76967c0ed370
Revises: 32e84e019965
Create Date: 2019-06-13 16:14:44.790124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76967c0ed370'
down_revision = '32e84e019965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'question', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
